### ISSUE TITLE
'Could not stop database' error after successfully running analysis scripts

### ISSUE THREAD

**Issue by james-tanner** [MontrealCorpusTools/ISCAN#181]
After running an analysis script on a non-Docker version of ISCAN, I (correctly) get a returned CSV but also the following error:

```
Traceback (most recent call last):
  File "polysyllabic.py", line 46, in <module>
    print('Finishing up!')
  File "/home/linguistics/jtanner/miniconda3/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/data/iscan-spade-server/pgdb/PolyglotDB/polyglotdb/utils.py", line 54, in ensure_local_database_running
    client.stop_database(database_name)
  File "/data/iscan-spade-server/pgdb/PolyglotDB/polyglotdb/client/client.py", line 142, in stop_database
    raise ClientError('Could not stop database: {}'.format(resp.text))
polyglotdb.exceptions.ClientError: Could not stop database: <html><head></head><body><h1>Server Error (500)</h1></body></html>
```

The server returns the following response:
```
"POST /api/databases/2/stop/ HTTP/1.1" 500 66
```

**Comment by mmcauliffe** [comment]
Ok, this should have better error messaging, but was ultimately caused by having another iscan server running on the same machine, with the check for ports in use, this should be caught long before the final stop REST API call.

**Comment by msonderegger** [comment]
Nice, thanks both.

On Mon, Feb 4, 2019 at 3:08 PM Michael McAuliffe <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok, this should have better error messaging, but was ultimately caused by having another iscan server running on the same machine, with the check for ports in use, this should be caught long before the final stop REST API call.
