### ISSUE TITLE
User administration interface in ISCAN

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/ISCAN#192]
There should be a page available for superusers that allows the following actions:

* Create new users
* Give users permissions for corpora
* Presets/default roles for user permissions (all permissions role, no detail inspection role, etc)

**Comment by msonderegger** [comment]
to elaborate / make sure I have correct -- this is what is to be implemented in ISCAN, effectively so that an admin can do "simple" permission management cases without having to actually use the Django permissions API.  Using Django remains always an option, and is the only option for non-preset/default cases.

**Comment by msonderegger** [comment]
🎉🎉
