### ISSUE TITLE
Tutorial for external script pipeline

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/ISCAN#197]
Once #193 is completed, there needs to be another tutorial on the readthedocs site detailing how it works with an external script (modern sibilant analysis?), in the style of the other tutorials on the site.

**Comment by msonderegger** [comment]
Michael G is doing this.

**Comment by msonderegger** [comment]
@MichaelGoodale finally tried out the tutorial, and asked Glasgow people to do so as well.

The tutorial works for me.  The one thing I would suggest changing is actually editing Waveform.R so it looks like this:
```
  def = function(waveform, startTime) {
    # Determine the value of the @amplitude slot according to whether
    # the [waveform] argument is mono or stereo...
    if (waveform@stereo) {
      # If the Wave object is stereo, ask the user which channel they would
      # like to use.
      message("Making a mono Waveform object from a stereo Wave object by averaging channels')
#Initializing a mono Waveform object from a stereo Wave object...")
channel <- 'Average'
# MS changed.
#flush.console()
#      channel <- select.list(title     = "Which channel would you like to use?",
#                             choices   = c("Left", "Right", "Average"),
#                             preselect = "Left", graphics = TRUE)
      if (channel == "Left") {
        wave.amp <- waveform@left
      } else if (channel == "Right") {
        wave.amp <- waveform@right
      } else if (channel == "Average") {
        wave.amp <- (waveform@left + waveform@right) / 2
      } else {
        wave.amp <- as.numeric(NA)
```

that is, instead of asking the user for stereo files how to make a mono file, it just automatically averages the channels. Otherwise the user has to select a number from a graphical menu n times, where n = # rows in input CSV, for any corpus (like ice-can) where the wav files aren't mono.

**Comment by msonderegger** [comment]
Michael G did the change above, and this can be closed. 

btw tutorial is here:
https://iscan.readthedocs.io/en/latest/tutorials_iscan.html#tutorial-4-custom-scripts

Thanks!
